language: php
php:
  - '7.0'

deploy:
- provider: s3
  access_key_id: AKIAJBPUKOCPF56NILPQ
  secret_access_key: &1
    secure: duKOvsEvDHmbOrggDjlDGJ/yxq25ACsA59LKFWqXhymhWKXuPAvLn6llSBzpNw8Ip5enbgM6gzMazxPyvjSVeN/LByFub/+lIyJQB+FvvsAezIbG9Px1BUIH8oiRbFiz6ENVXVOIue76ccFXdFc800GA2QHTEaZU/NS9l4GV+dXgnwzbwcHw3+7dGHWyCtNDxnXYFA0VrlX8ILt0H01u36nlvs1SmuSM+/8uC7wJPY5qonFNixrVcFVNn7BMtN+as/G1gac1GxOXujAN+FalqlE7HxSqV+oeaBvnbHVI/NlyhMuTUn40cMGbhpczqX0jVFETHouOv3ymwxmeFqekJzMmIgcNecjiFPiqd9FXXKQwnDHziI6/05yAbhDPMR19/ShVogF8ReNwltJ3XCK9DO5f+R8af/m3tkj9tmDNmrlhHCTxbcUbpxgF1dhPmCv59jsPJ1JwP836hw3M0E10EuH4NOpjSw77z5z7vigQYgCRvhhS2e8MOk9ZhAeBpzjtXxtCClKW+GrwfG9TgtzuRSDkie5KiYMbrVtmdpHtdxQGA0uzUK8HyEEa5HBtsQBlg6B5qKbB6NG7bmpXlLJ1ZoJAIaumx3eAyckFRP7hWIZYLUWe8qojBhFvPRYfViM9VBv3kMEHKWh2T7EsXOAsG3KtTSdmoaQTJJbE3+/px7c=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: Temdi/AWS-Project
  bucket: ''
- provider: codedeploy
  access_key_id: AKIAJBPUKOCPF56NILPQ
  secret_access_key: *1
  bucket: ''
  key: ''
  bundle_type: ''
  application: AWS-Project
  deployment_group: CR-AWS-Project
  on: *2
  
before_deploy:
- mkdir -p dpl_cd_upload
- mv '' dpl_cd_upload/''
